#!/bin/bash


file1="$1"
file2="$2"
output1="difftest1.out"
output2="difftest2.out"
seednum=42 
filepath=$(cd "$(dirname "$0")"; pwd)

rm -rf $file1
mkdir $file1

rm -rf $file2
mkdir $file2

cd $filepath"/"$file1
make testdominion
./testdominion $seednum > $output1  
cp $output1 $filepath 

cd $filepath"/"$file2
make testdominion
./testdominion $seednum > $output2  
cp $output2 $filepath

cd $filepath
rm -rf $file1
rm -rf $file2
rm diff.out
diff $filepath"/"$output1 $filepath"/"$output2 > diff.out

if [ $? -eq 0 ] 
	then
		echo 'TEST PASSED'
	else
		echo 'TEST FAILED'
fi